version: 2.1

jobs:
  rice-cooker-test:
    docker:
      - image: google/dart:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dart pub get

      - run:
          name: Run tests
          command: dart test

workflows:
  rice-cooker-workflow:
    jobs:
      - rice-cooker-test